### ISSUE TITLE
A little mistake I found ?

### ISSUE THREAD

**Issue by LT-ZHONG** [Shiaoming/stair-perception#4]
@Shiaoming 

I think I found a little mistake in the function `StairDetection::computeVectorPlaneInfo`

> https://github.com/Shiaoming/stair-perception/blob/b4989552face19ba93ba47744578c538360b6cc9/modules/stairperception/StairPerception.cpp#L1313-L1316

I guess you want to calculate every plane's principle centre after we get the `points_max` and `points_min`. And I think what you want to do is as follow.

`plane.pcenter.x = (points_max[0].x + points_min[0].x)/2; `
`plane.pcenter.y = (points_max[0].y + points_min[0].y)/2; `
`plane.pcenter.z = (points_max[0].z + points_min[0].z)/2; `

I am not sure if I am right or not ?

**Comment by Shiaoming** [comment]
@LT-ZHONG 
Yes, it's another mistake.

Thank you for your correction.
