### ISSUE TITLE
Two small questions on computing line from 2 planes

### ISSUE THREAD

**Issue by LT-ZHONG** [Shiaoming/stair-perception#5]
Hi @Shiaoming 
Sorry to bother you again. 
This time I ran into a small question when reading the source code.
In the function

> https://github.com/Shiaoming/stair-perception/blob/3cd6222f87d5635066bc98c57548fa900490bef4/modules/stairperception/StairPerception.cpp#L1123-L1127

you want to compute the intersection line of 2 planes. I am not quite understand why you calculate parameter `t` in this way. 
I know `t` is the parameter in the vector equation of line, and I just wonder the reason why `t` is calculated in this way.

Then `t` is used to calculate another point on the line, whose coordinate is represented by variable `x` `y` `z` .

> https://github.com/Shiaoming/stair-perception/blob/3cd6222f87d5635066bc98c57548fa900490bef4/modules/stairperception/StairPerception.cpp#L1129-L1131

And another place that puzzles me is that what is the meaning of `line.h` and `line.d` ?

> https://github.com/Shiaoming/stair-perception/blob/3cd6222f87d5635066bc98c57548fa900490bef4/modules/stairperception/StairPerception.cpp#L1140-L1141

Does it refer to the height and width of the steps , just like the annotation I made in the following picture ?

![Selection_001](https://user-images.githubusercontent.com/49059253/87772751-bbb17a00-c854-11ea-851e-7e658d46ecd9.png)

Thanks !

**Comment by Shiaoming** [comment]
**1. The intersection point of line and plane xoy**
> https://github.com/Shiaoming/stair-perception/blob/3cd6222f87d5635066bc98c57548fa900490bef4/modules/stairperception/StairPerception.cpp#L1123-L1131

The line is <img src="https://latex.codecogs.com/gif.latex?\frac{x-x_0}{n_1}&space;=\frac{y-y_0}{n_2}&space;=\frac{z-z_0}{n_3}&space;=t" title="\frac{x-x_0}{n_1} =\frac{y-y_0}{n_2} =\frac{z-z_0}{n_3} =t" />, so we have: <img src="https://latex.codecogs.com/gif.latex?\begin{cases}&space;x=tn_1&plus;x_0&space;\\&space;y=tn_2&plus;y_0&space;\\&space;y=tn_2&plus;z_0&space;\end{cases}" title="\begin{cases} x=tn_1+x_0 \\ y=tn_2+y_0 \\ y=tn_2+z_0 \end{cases}" />

then the intersection of line and the plane <img src="https://latex.codecogs.com/gif.latex?n_1x&plus;n_2y&plus;n_3z=0" title="n_1x+n_2y+n_3z=0" /> can be computed as follows:
<img src="https://latex.codecogs.com/gif.latex?n_1(tn_1&plus;x_0)&plus;n_2(tn_2&plus;y_0)&plus;n_3(tn_3&plus;z_0)&space;=&space;0" title="n_1(tn_1+x_0)+n_2(tn_2+y_0)+n_3(tn_3+z_0) = 0" /> 
==>
<img src="https://latex.codecogs.com/gif.latex?t&space;=&space;-\frac{n_1x_0&plus;n_2y_0&plus;n_3z_0}{n_1^2&plus;n_2^2&plus;n_3^2}" title="t = -\frac{n_1x_0+n_2y_0+n_3z_0}{n_1^2+n_2^2+n_3^2}" />
then:
<img src="https://latex.codecogs.com/gif.latex?\left\{\begin{matrix}&space;x=n_1t&plus;x_0\\&space;y=n_2t&plus;y_0\\&space;z=n_3t&plus;z_0&space;\end{matrix}\right." title="\left\{\begin{matrix} x=n_1t+x_0\\ y=n_2t+y_0\\ z=n_3t+z_0 \end{matrix}\right." />

**2. `line.h` is VD, `line.d` is HD.**

**Comment by LT-ZHONG** [comment]
I understand. 
Thanks for your answer.
