### ISSUE TITLE
does it work for downstairs ?

### ISSUE THREAD

**Issue by siddharthcb** [Shiaoming/stair-perception#6]
hi,
thanks for your work.
Just wondering if this package is also applicable for downstairs. what are your thoughts about it?

**Comment by Shiaoming** [comment]
This depends on the captured point cloud. If the stair structure is well captured, the stair should be detected.

Although we considered the case that the vertical plane of the step is not visible, in the case of downstairs, all the vertical planes of the step are not visible, which may lead to the failure of this algorithm in the correct detection and modeling.

**Comment by siddharthcb** [comment]
Thank you.
